#cloud-config
package_upgrade: true
packages:
  - curl
  - openjdk-17-jre-headless
runcmd:
  - curl -sL https://downloads.metabase.com/v0.49.6/metabase.jar -o metabase.jar
  - java -jar metabase.jar &
